config/routes.rb
Rails.application.routes.draw do
  resources :toilets
  resources :gifs
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'gifs#index'
  get "/discord_start" => "botcontrol#discord_start"
  get "/discord_stop" => "botcontrol#discord_stop"
  get "/updatedoc" => "docs#update"

  telegram_webhook TelegramWebhooksController
  get "/update" => "gifgetter#gifchecker"
  get '/:id' => "shortener/shortened_urls#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alltime.rb
class Alltime < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/docpoint.rb
class Docpoint < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :telegram_user
end

app/models/gif.rb
class Gif < ApplicationRecord
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/models/newquote.rb
class Newquote < ApplicationRecord
end

app/models/opt.rb
class Opt < ApplicationRecord
end

app/models/private_message_log.rb
class PrivateMessageLog < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :telegram_user
	belongs_to :toilet
end

app/models/telegram_user.rb
class TelegramUser < ApplicationRecord
	has_many :reviews
	has_many :toilets, :through => :reviews
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/toilet.rb
class Toilet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  before_action :set_gif, only: [:show, :edit, :update, :destroy]  
  #before_action :authenticate_user!


  def ID
    "Google Drive Id"
  end
  # GET /gifs
  # GET /gifs.json
  def index
    @gifs = Gif.all
  end

  # GET /gifs/1
  # GET /gifs/1.json
  def show
  end

  # GET /gifs/new
  def new
    @gif = Gif.new
  end

  # GET /gifs/1/edit
  def edit
  end

  # POST /gifs
  # POST /gifs.json
  def create
    @gif = Gif.new(gif_params)

    respond_to do |format|
      if @gif.save
        format.html { redirect_to @gif, notice: 'Gif was successfully created.' }
        format.json { render :show, status: :created, location: @gif }
      else
        format.html { render :new }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifs/1
  # PATCH/PUT /gifs/1.json
  def update
    respond_to do |format|
      if @gif.update(gif_params)
        format.html { redirect_to @gif, notice: 'Gif was successfully updated.' }
        format.json { render :show, status: :ok, location: @gif }
      else
        format.html { render :edit }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifs/1
  # DELETE /gifs/1.json
  def destroy
    @gif.destroy
    respond_to do |format|
      format.html { redirect_to gifs_url, notice: 'Gif was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gif
      @gif = Gif.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gif_params
      params.require(:gif).permit(:gif_name, :description, :gif_tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def self.authorize 
        oob_url = "urn:ietf:wg:oauth:2.0:oob".freeze
        application_name = "Elеktro prostotii".freeze
        file = File.open("token.yaml", "w")
        file.write "---\ndefault: "
        file.write(ENV["DOCS_AUTH_TOKEN"].to_json)
        file.close
        credentials_json = (JSON.parse(ENV["DOCS_CREDENTIALS"])).freeze
        token_path = "token.yaml".freeze
        scope = Google::Apis::DocsV1::AUTH_DOCUMENTS_READONLY
        client_id = Google::Auth::ClientId.from_hash credentials_json
        token_store = Google::Auth::Stores::FileTokenStore.new file: token_path
        authorizer = Google::Auth::UserAuthorizer.new client_id, scope, token_store
        user_id = "default"
        credentials = authorizer.get_credentials user_id
        if credentials.nil?
            url = authorizer.get_authorization_url base_url: oob_url
            puts "Open the following URL in the browser and enter the " \
                "resulting code after authorization:\n" + url
            code = gets
            credentials = authorizer.get_and_store_credentials_from_code(
                user_id: user_id, code: code, base_url: oob_url
            )
        end
        credentials
     end
end

app/helpers/botcontrol_helper.rb
module BotcontrolHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/gifgetter_helper.rb
module GifgetterHelper
end

app/helpers/gifs_helper.rb
module GifsHelper
end

app/helpers/toilets_helper.rb
module ToiletsHelper
end

app/views/gifs/_form.html.erb
<div class="form_inputs">
  <%= form_for(gif) do |f| %>
    <% if gif.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(gif.errors.count, "error") %> prohibited this gif from being saved:</h2>

        <ul>
        <% gif.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :gif_name %>
      <%= f.text_field :gif_name,  class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :Description %>
      <%= f.text_field :description,  class: "form-control" %>
    </div>

  <!--   <div class="field">
      <%= f.label :gif_tags %>
      <%= f.text_field :gif_tags %>
    </div> -->

    <div class="actions">
      <%= f.submit class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/gifs/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			
		</div>
		<div class="col-lg- form_centered">
			<h1>Editing Gif</h1>
			<div>
				<%= render 'form', gif: @gif %>
			</div>
			<%= link_to 'Show', @gif, class: "btn btn-primary"  %> |
			<%= link_to 'Back', gifs_path, class: "btn btn-warning"  %>
		</div>
	</div>
</div>

app/views/gifs/index.html.erb
<div class="col-lg-12">
  <h1>Gifs</h1>
  <table>
    <thead>
      <tr>
        <th><h2>Gif name</h2></th>
        <th><h2>Description</h2></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @gifs.each do |gif| %>
        <tr><h3>
          <td><h3><%= gif.gif_name %></h3></td>
          <td><h3><%= gif.description %></h3></td>
        <!--  <td><%= gif.gif_tags %></td>-->
      </h3>
          <td><%= link_to 'Show', gif ,class: "btn btn-primary"%></td>
          <td><%= link_to 'Edit', edit_gif_path(gif), class: "btn btn-warning" %></td>
          <td><%= link_to 'Destroy', gif, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Update", "/update", class: "btn btn-primary"%>
  <%= link_to 'New Gif', new_gif_path, class: "btn btn-success" %>
</div>
<!-- <div class="col-lg-4 align-content-center">
  <h1>Toilets Functionality</h1>
  <%= link_to "Toilets", "/toilets", class: "btn btn-success"%>
</div> -->

app/views/gifs/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			
		</div>
		<div class="col-lg- form_centered">
			<h1>New Gif</h1>

			<div class="">
				<%= render 'form', gif: @gif %>	
			</div>

			<%= link_to 'Back', gifs_path, class: "btn btn-warning" %>
		</div>
	</div>
</div>

app/views/gifs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5">
      
    </div>
    <div class="col-lg-5 form_centered">
		<h2>
		  <strong>Gif name:</strong>
		  <%= @gif.gif_name %>
		</h2>

		<h2>
		  <strong>Gif description:</strong>
		  <%= @gif.description %>
		</h2>
		<!-- 
		<h2>
		  <strong>Gif tags:</strong>
		  <%= @gif.gif_tags %>
		</h2> -->

		<%= link_to 'Edit', edit_gif_path(@gif), class: "btn btn-primary" %> |
		<%= link_to 'Back', gifs_path, class: "btn btn-warning" %>
	</div>
</div>