config/routes.rb
Rails.application.routes.draw do
  resources :toilets
  resources :gifs
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'gifs#index'
  get "/discord_start" => "botcontrol#discord_start"
  get "/discord_stop" => "botcontrol#discord_stop"
  get "/updatedoc" => "docs#update"

  telegram_webhook TelegramWebhooksController
  get "/update" => "gifgetter#gifchecker"
  get '/:id' => "shortener/shortened_urls#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alltime.rb
class Alltime < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/docpoint.rb
class Docpoint < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :telegram_user
end

app/models/gif.rb
class Gif < ApplicationRecord
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/models/newquote.rb
class Newquote < ApplicationRecord
end

app/models/opt.rb
class Opt < ApplicationRecord
end

app/models/private_message_log.rb
class PrivateMessageLog < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :telegram_user
	belongs_to :toilet
end

app/models/telegram_user.rb
class TelegramUser < ApplicationRecord
	has_many :reviews
	has_many :toilets, :through => :reviews
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/toilet.rb
class Toilet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/toilets_controller.rb
class ToiletsController < ApplicationController
  require "telegram_webhooks_controller"
  before_action :set_toilet, only: [:show, :edit, :update, :destroy]

  # GET /toilets
  # GET /toilets.json
  def index
    @toilets = Toilet.all
  end

  # GET /toilets/1
  # GET /toilets/1.json
  def show
  end

  # GET /toilets/new
  def new
    @toilet = Toilet.new
  end

  # GET /toilets/1/edit
  def edit
  end

  # POST /toilets
  # POST /toilets.json
  def create
    @toilet = Toilet.new(toilet_params)

    respond_to do |format|
      if @toilet.save
        format.html { redirect_to @toilet, notice: 'Toilet was successfully created.' }
        format.json { render :show, status: :created, location: @toilet }
      else
        format.html { render :new }
        format.json { render json: @toilet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toilets/1
  # PATCH/PUT /toilets/1.json
  def update
    respond_to do |format|
      if @toilet.update(toilet_params)
        format.html { redirect_to @toilet, notice: 'Toilet was successfully updated.' }
        format.json { render :show, status: :ok, location: @toilet }
      else
        format.html { render :edit }
        format.json { render json: @toilet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toilets/1
  # DELETE /toilets/1.json
  def destroy
    @toilet.destroy
    respond_to do |format|
      format.html { redirect_to toilets_url, notice: 'Toilet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_toilet
      @toilet = Toilet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def toilet_params
      params.require(:toilet).permit(:name, :location, :x, :y, :maps_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def self.authorize 
        oob_url = "urn:ietf:wg:oauth:2.0:oob".freeze
        application_name = "Elеktro prostotii".freeze
        file = File.open("token.yaml", "w")
        file.write "---\ndefault: "
        file.write(ENV["DOCS_AUTH_TOKEN"].to_json)
        file.close
        credentials_json = (JSON.parse(ENV["DOCS_CREDENTIALS"])).freeze
        token_path = "token.yaml".freeze
        scope = Google::Apis::DocsV1::AUTH_DOCUMENTS_READONLY
        client_id = Google::Auth::ClientId.from_hash credentials_json
        token_store = Google::Auth::Stores::FileTokenStore.new file: token_path
        authorizer = Google::Auth::UserAuthorizer.new client_id, scope, token_store
        user_id = "default"
        credentials = authorizer.get_credentials user_id
        if credentials.nil?
            url = authorizer.get_authorization_url base_url: oob_url
            puts "Open the following URL in the browser and enter the " \
                "resulting code after authorization:\n" + url
            code = gets
            credentials = authorizer.get_and_store_credentials_from_code(
                user_id: user_id, code: code, base_url: oob_url
            )
        end
        credentials
     end
end

app/helpers/botcontrol_helper.rb
module BotcontrolHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/gifgetter_helper.rb
module GifgetterHelper
end

app/helpers/gifs_helper.rb
module GifsHelper
end

app/helpers/toilets_helper.rb
module ToiletsHelper
end

app/views/toilets/_form.html.erb
<div class="form_inputs">
  <%= form_for(toilet) do |f| %>
    <% if toilet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(toilet.errors.count, "error") %> prohibited this toilet from being saved:</h2>

        <ul>
        <% toilet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name,  class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :location %>
      <%= f.text_field :location,  class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :x %>
      <%= f.text_field :x,  class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :y %>
      <%= f.text_field :y,  class: "form-control"%>
    </div>

<!--     <div class="form-group">
      <%= f.label :maps_link %>
      <%= f.text_field :maps_link,  class: "form-control" %>
    </div> -->

    <div class="actions">
      <%= f.submit class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/toilets/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			
		</div>
		<div class="col-lg- form_centered">
			<h1>Editing Toilet</h1>
			<div>
				<%= render 'form', toilet: @toilet %>
			</div>
			<%= link_to 'Show', @toilet, class: "btn btn-primary" %> |
			<%= link_to 'Back', toilets_path, class: "btn btn-warning" %>
		</div>
	</div>
</div>

app/views/toilets/index.html.erb
<div class="col-lg-12">
  <h1>Toilets</h1>

  <table>
    <thead>
      <tr>
        <th><h2>Name</h2></th>
        <th><h2>Location</h2></th>
        <th><h2>X</h2></th>
        <th><h2>Y</h2></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @toilets.each do |toilet| %>
        <tr>
          <td><h3><%= toilet.name %></h3></td>
          <td><h3><%= toilet.location %></h3></td>
          <td><h3><%= toilet.x %></h3></td>
          <td><h3><%= toilet.y %></h3></td>
          <td><%= link_to 'Show', toilet,class: "btn btn-primary"%></td>
          <td><%= link_to 'Edit', edit_toilet_path(toilet),class: "btn btn-warning" %></td>
          <td><%= link_to 'Destroy', toilet, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
          <td><hr></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Toilet', new_toilet_path, class: "btn btn-success" %>
</div>

app/views/toilets/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			
		</div>
		<div class="col-lg- form_centered">
			<h1>New Toilet</h1>
			<div>
			<%= render 'form', toilet: @toilet %>
			</div>
			<%= link_to 'Back', toilets_path,class: "btn btn-warning"  %>
		</div>
	</div>
</div>

app/views/toilets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      
    </div>
    <div class="col-lg-5 form_centered">
      <h2>
        <strong>Name:</strong>
        <%= @toilet.name %>
      </h2>

      <h2>
        <strong>Location:</strong>
        <%= @toilet.location %>
      </h2>

      <h2>
        <strong>X:</strong>
        <%= @toilet.x %>
      </h2>

      <h2>
        <strong>Y:</strong>
        <%= @toilet.y %>
      </h2>

      <%= link_to 'Edit', edit_toilet_path(@toilet), class: "btn btn-primary" %> |
      <%= link_to 'Back', toilets_path, class: "btn btn-warning" %>
    </div>
  </div>
</div>